name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout dùng bản v4 (Node 24)
      - uses: actions/checkout@v4

      # Bước 2: Tạo Snake dùng bản v3 (Mới nhất)
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: nguyenkhaan
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif

      # Bước 3: Đẩy lên branch output dùng bản v3 (Node 24)
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
